name: Contracts

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/contracts.yml"
      - "LUSDChickenBonds/**"

  pull_request:
    paths:
      - ".github/workflows/contracts.yml"
      - "LUSDChickenBonds/**"

jobs:
  dev-test:
    name: Dev tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # TODO pin this down once Foundry starts versioning releases
          version: nightly

      - name: Run dev tests
        working-directory: LUSDChickenBonds
        run: >-
          forge test
          -vvv
          --match-contract ChickenBondManagerDevTest

  mainnet-test:
    name: Mainnet tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # TODO pin this down once Foundry starts versioning releases
          version: nightly

      - name: Run mainnet tests
        working-directory: LUSDChickenBonds
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: >-
          forge test
          -vvv
          --match-contract ChickenBondManagerMainnetTest
          --fork-url ${{ secrets.ETH_RPC_URL }}
